# Generated by Django 3.0.5 on 2020-05-05 10:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Entradas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entradas_blog',
            managers=[
                ('articulos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='entradas_blog',
            name='cuerpo',
            field=models.TextField(max_length=20000),
        ),
    ]
