# Generated by Django 3.0.5 on 2020-05-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entradas', '0002_auto_20200505_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas_blog',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
