# Generated by Django 3.0.5 on 2020-05-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entradas', '0003_auto_20200506_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas_blog',
            name='contra',
            field=models.CharField(default='contraseña', max_length=10),
        ),
    ]
