# Generated by Django 3.0.5 on 2020-05-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entradas', '0006_remove_entradas_blog_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas_blog',
            name='contra',
            field=models.CharField(default='contraseña', max_length=12, verbose_name='contraseña'),
        ),
    ]
