# Generated by Django 3.0.5 on 2020-05-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entradas', '0007_auto_20200506_1633'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entradas_blog',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='entradas_blog',
            name='slug',
            field=models.SlugField(default='slug', max_length=80),
            preserve_default=False,
        ),
    ]
