# Generated by Django 3.0.5 on 2020-05-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entradas', '0009_auto_20200513_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradas_blog',
            name='contra',
        ),
    ]
