# Generated by Django 3.0.5 on 2020-05-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entradas', '0011_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='comentario',
            new_name='cuerpo',
        ),
    ]
